### ISSUE TITLE
blaze-builder 0.4 support

### ISSUE THREAD

**Issue by snoyberg** [snapframework/snap-core#227] opened 2015-03-22 16:56 UTC
Original issue: https://github.com/fpco/stackage/issues/442

Are there any plans to release a new version of snap-core and snap-server with blaze-builder 0.4 support? All other packages with a restrictive upper bound look like they will soon be addressed, which would mean snap is the only package holding things back.

**Comment by gregorycollins** [comment] 2015-03-23 06:36
I'm still porting the code to the 1.0 branch -- fairly extensive changes have been required there and will need to be backported.

**Comment by snoyberg** [comment] 2015-03-23 06:37
Can you give me an idea of what the timeframe looks like? I'd ideally want to include blaze-builder 0.4 in LTS 2, which is going to be released on April 1.

**Comment by gregorycollins** [comment] 2015-03-23 15:41
It's possible I can get it done by then but I can't commit to it right now.

**Comment by hvr** [comment] 2015-03-29 10:01
@snoyberg btw, part of the problem is probably that https://hackage.haskell.org/package/blaze-builder-enumerator is blocking `blaze-builder-0.4` as well...

**Comment by snoyberg** [comment] 2015-03-29 10:23
I was under the impression, perhaps mistakenly, that fixing this would
involve moving away from that library. In any event, from a stackage
standpoint, it's only there to support snap, so if snap decides to remove
the dependency, stackage can too.

**Comment by meiersi** [comment] 2015-03-29 17:00
I'll have another go at blaze-builder-ennumerator over easter.

**Comment by manny-fp** [comment] 2015-03-30 22:57
After applying https://github.com/meiersi/blaze-builder-enumerator/pull/5 and relaxing the constraint on blaze-builder, snap-core seems to build with blaze-builder-0.4.*.

**Comment by snoyberg** [comment] 2015-03-31 14:19
Bumping this, a simple relaxing of version bounds is the only thing holding back blaze-builder 0.4 support in LTS 2.

**Comment by gregorycollins** [comment] 2015-03-31 15:01
@snoyberg I think that is true for snap-core but not for snap-server, I will need to do some work there.

**Comment by snoyberg** [comment] 2015-03-31 15:40
I just bumped the upper bounds on both snap-core and snap-server, and ran

    cabal install --constraint 'blaze-builder >= 0.4' ./snap-core-0.9.6.4/ ./snap-server-0.9.4.6/ --run-tests

It completed flawlessly, no build or test failures.

**Comment by gregorycollins** [comment] 2015-03-31 15:53
OK then, that's good news. If that's all that's involved, I should be able to get to it tonight.

**Comment by snoyberg** [comment] 2015-04-01 04:24
Sigh. I think it's past "tonight," and it's looking like this won't get resolved. For one last shot, pinging @mightybyte as well. It's disappointing that two 1-byte patches aren't getting pushed, for apparently no reason.

**Comment by ChristopherBiscardi** [comment] 2015-04-01 04:49
>Sigh. I think it's past "tonight,"

It's not even 10PM yet in our timezone... (although I understand it's ~8am in yours)

**Comment by snoyberg** [comment] 2015-04-01 04:49
Yes, that's your timezone... I thought Gregory is still in Zurich. Am I
mistaken?

**Comment by snoyberg** [comment] 2015-04-01 04:50
If this is still going to happen in the next few hours, I'm happy. I'd
written this off as not going to happen in time, which would be incredibly
unfortunate for users.

**Comment by meiersi** [comment] 2015-04-01 06:39
As far as I know Gregory is in SF.
Am 01.04.2015 06:49 schrieb "Michael Snoyman" <notifications@github.com>:

> Yes, that's your timezone... I thought Gregory is still in Zurich. Am I
> mistaken?
>
> On Wed, Apr 1, 2015 at 7:49 AM Christopher Biscardi <

**Comment by snoyberg** [comment] 2015-04-01 06:46
I think you're right. That's what I remembered, but then I saw https://github.com/gregorycollins, which said Zurich.

**Comment by gregorycollins** [comment] 2015-04-01 15:16
The fix to blaze-builder-enumerator doesn't work, it's broken on GHC 7.6.3. I'm working on a patch. And @snoyberg, you can keep your disapproval to yourself. Working on Haskell is not my full time job (I had Google work to do last night that preempted) and this deadline of yours is arbitrary as far as I'm concerned.

**Comment by gregorycollins** [comment] 2015-04-01 16:16
Compatible version of 0.9 is ready to go out once https://github.com/meiersi/blaze-builder-enumerator/pull/6 is merged and released.

**Comment by snoyberg** [comment] 2015-04-01 16:55
Thank you, much appreciated. If you can ping me when it's out, that would
be great.

**Comment by snoyberg** [comment] 2015-04-01 17:12
Alright, blaze-builder-enumerator-0.2.1.0 with @gregorycollins's extra commit is now on Hackage.

**Comment by gregorycollins** [comment] 2015-04-01 17:54
Released snap-core 0.9.7.0 and snap-server 0.9.5.0, which should be compatible with latest changes.

**Closed by gregorycollins** 2015-04-01 17:54 UTC

**Comment by snoyberg** [comment] 2015-04-01 18:07
Thank you!
